[WIP] Try to replace all gulp with webpack
screepers/screeps-typescript-starter pull request #45
Opened 2017-05-12 04:02 UTC by bryanbecker

Ref: https://github.com/screepers/screeps-typescript-starter/issues/44

This is a WIP change.  Currently I've just stripped the npm modules back to nothing to try and restart.

**Changes:**
- typescript update to latest (2.4.0)
- ts-loader replaced with awesome-typescript-loader
Awesome can fork the typechecker and emitter leading to faster
compile times

2017-05-13 14:05 UTC, resir014 requested changes
Awesome work! I've put some minor style guide suggestions, but other than that, it's good to go.

2017-05-13 14:05 UTC, resir014 commented on config/credentials.example.json
> +  "email": 'EMAIL',
replace the single quotes on this file with double quotes, as per the [JSON specifications](http://www.json.org/).

2017-05-13 14:05 UTC, resir014 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
This should work fine with `mocha`. I'll test it on my personal repo just to make sure.

Not sure about coverage though.

2017-05-13 17:33 UTC, resir014 commented
I've also done some more extensive tests on, well, tests, and I've managed to run the tests fine with minimal tweaks.

You'll need to add the following packages:

```sh
$ npm install --save-dev @types/mocha @types/chai mocha chai ts-node
```

**Some caveats:** Setting `strict: true` on your `tsconfig.json` (basically, using strict mode) will cause the tests to break due to `noImplicitAny` errors on `test/mock/game.ts` (the whole file mocks the entire game's constants so some TS rules are ignored). Can we actually suppress these errors for this one file only?

2017-05-13 23:19 UTC, bryanbecker commented
What is causing the errors... mocha or tslint?  We can add files or directories to be excluded by tslint (or any module, really), in the config (see [this line](https://github.com/screepers/screeps-typescript-starter/pull/45/files#diff-302de8d679dbd724686b4a0b44b48f0cR109))

I couldn't get the tests to run via a simple `./node_modules/mocha/bin/mocha` command, but that may be because it expects things to be compiled (complained about `__REVISION__` is not set)

Re integration, I found two modules:

[mocha webpack](https://github.com/zinserjan/mocha-webpack) which seems more full features.  It's run with the `mocha-webpack` command, and has a watch mode.  Not sure if it integrates well into our existing webpack config, though (i.e. we may be face with with "pick one: mocha-webpack watch or webpack watch"

[mocha loader](https://github.com/webpack-contrib/mocha-loader) this seems the safer bet to me.  It integrates into the existing webpack config, and is run as part of the build.

Question: is [sinon](https://github.com/sinonjs/sinon/) still needed in the package?  Sinon, jshint, intanbul & nyc seem to be the major packages that haven't made it into "2.0", yet

Last, is testing "opt-in" or "opt-out".  There's a few ways to put it into the existing config.

1. Add testing into `config.default.js`, with README telling how to remove.  This will enforce testing in all environments unless specifically removed in an environment config
2. Add to `config.dev.js`.  This will have the same affect for people just starting, since `dev` is  the only environment
3. Make new environment file
4. "Hack" it with env vars like so:

```js
  // regular config to run testing with any file matching /test.js$/ regex (except in node_modules)
    rules: [{
      test: /test.js$/,
      use: 'mocha-loader',
      exclude: /node_modules/,
    }]

  // HACK with something like:
if ("[testing] === true") {
  Config.module.rules.push(\* the above rule object *\);
}
```

Setting up the config for option 4 has a lot of interesting tradeoffs.

For one, it will encourage a minor config refactor.  While the config currently is just a really large object with values filled in.  We could refactor to something like:

```js
//... snip
module: = getModules();
// .. snip

function getModules() {
  // returns the modules object
}
``

The tradeoff is that it might accidentally balloon into a back-from-the-dead gulpfile monstrosity

2017-05-14 00:35 UTC, bryanbecker commented
Hold off on the merge.  I made another local branch with a config that I think is much more maintainable and organized.

Still need to make sure a few things work correctly, though

2017-05-14 02:58 UTC, resir014 commented
@bryanbecker 

> What is causing the errors... mocha or tslint?

I think it was `mocha`, since the test is written on TS as well we had to use the `ts-node` runtime when passing the code to `mocha`

2017-05-14 02:59 UTC, resir014 approved these changes

2017-05-14 03:00 UTC, resir014 commented
Anyways, I approved the changes but I'll wait for your end of the work, then I'll give it a go in my codebase again.

2017-05-14 05:05 UTC, bryanbecker commented
OK, everything is in typescript now... still need to update the README to match, but config is much easier to programmatically alter, now

Re:  Mocha:  I think some additional tool is needed (Karma, maybe?), since it needs to compile the TS before running the tests.

[Mocha Webpack](https://github.com/zinserjan/mocha-webpack)  I think can handle it, too... The issue is that it needs to know where to import the files/modules from

2017-05-14 05:53 UTC, resir014 commented
Yeah, you're right. /:

This might take a while to figure out, so do you want me merge this and look into re-integrating the testing framework on a separate PR?

2017-05-14 06:18 UTC, bryanbecker commented
Sure, let me update the README, then lets merge and let some people try it out

2017-05-14 06:57 UTC, bryanbecker commented
Done

2017-05-14 11:00 UTC, resir014 commented
Alright, thanks! Merging now.

2017-05-14 11:00 UTC, merged